/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SeriesIdRouteImport } from './routes/series.$id'
import { Route as MovieIdRouteImport } from './routes/movie.$id'
import { Route as BrowseKindRouteImport } from './routes/browse.$kind'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminLicensesRouteImport } from './routes/admin.licenses'
import { Route as AdminCodesRouteImport } from './routes/admin.codes'
import { Route as WatchKindIdRouteImport } from './routes/watch.$kind.$id'
import { Route as ApiDebugXtreamRouteImport } from './routes/api.debug.xtream'
import { Route as ApiPublicStreamKindFileRouteImport } from './routes/api.public.stream.$kind.$file'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SeriesIdRoute = SeriesIdRouteImport.update({
  id: '/series/$id',
  path: '/series/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseKindRoute = BrowseKindRouteImport.update({
  id: '/browse/$kind',
  path: '/browse/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLicensesRoute = AdminLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCodesRoute = AdminCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => AdminRoute,
} as any)
const WatchKindIdRoute = WatchKindIdRouteImport.update({
  id: '/watch/$kind/$id',
  path: '/watch/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugXtreamRoute = ApiDebugXtreamRouteImport.update({
  id: '/api/debug/xtream',
  path: '/api/debug/xtream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStreamKindFileRoute = ApiPublicStreamKindFileRouteImport.update({
  id: '/api/public/stream/$kind/$file',
  path: '/api/public/stream/$kind/$file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bootstrap': typeof BootstrapRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/redeem': typeof RedeemRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/browse/$kind': typeof BrowseKindRoute
  '/movie/$id': typeof MovieIdRoute
  '/series/$id': typeof SeriesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/debug/xtream': typeof ApiDebugXtreamRoute
  '/watch/$kind/$id': typeof WatchKindIdRoute
  '/api/public/stream/$kind/$file': typeof ApiPublicStreamKindFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bootstrap': typeof BootstrapRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/redeem': typeof RedeemRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/browse/$kind': typeof BrowseKindRoute
  '/movie/$id': typeof MovieIdRoute
  '/series/$id': typeof SeriesIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/debug/xtream': typeof ApiDebugXtreamRoute
  '/watch/$kind/$id': typeof WatchKindIdRoute
  '/api/public/stream/$kind/$file': typeof ApiPublicStreamKindFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bootstrap': typeof BootstrapRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/redeem': typeof RedeemRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/browse/$kind': typeof BrowseKindRoute
  '/movie/$id': typeof MovieIdRoute
  '/series/$id': typeof SeriesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/debug/xtream': typeof ApiDebugXtreamRoute
  '/watch/$kind/$id': typeof WatchKindIdRoute
  '/api/public/stream/$kind/$file': typeof ApiPublicStreamKindFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bootstrap'
    | '/favorites'
    | '/login'
    | '/more'
    | '/redeem'
    | '/search'
    | '/settings'
    | '/admin/codes'
    | '/admin/licenses'
    | '/admin/packages'
    | '/admin/users'
    | '/browse/$kind'
    | '/movie/$id'
    | '/series/$id'
    | '/admin/'
    | '/api/debug/xtream'
    | '/watch/$kind/$id'
    | '/api/public/stream/$kind/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bootstrap'
    | '/favorites'
    | '/login'
    | '/more'
    | '/redeem'
    | '/search'
    | '/settings'
    | '/admin/codes'
    | '/admin/licenses'
    | '/admin/packages'
    | '/admin/users'
    | '/browse/$kind'
    | '/movie/$id'
    | '/series/$id'
    | '/admin'
    | '/api/debug/xtream'
    | '/watch/$kind/$id'
    | '/api/public/stream/$kind/$file'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bootstrap'
    | '/favorites'
    | '/login'
    | '/more'
    | '/redeem'
    | '/search'
    | '/settings'
    | '/admin/codes'
    | '/admin/licenses'
    | '/admin/packages'
    | '/admin/users'
    | '/browse/$kind'
    | '/movie/$id'
    | '/series/$id'
    | '/admin/'
    | '/api/debug/xtream'
    | '/watch/$kind/$id'
    | '/api/public/stream/$kind/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BootstrapRoute: typeof BootstrapRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  MoreRoute: typeof MoreRoute
  RedeemRoute: typeof RedeemRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  BrowseKindRoute: typeof BrowseKindRoute
  MovieIdRoute: typeof MovieIdRoute
  SeriesIdRoute: typeof SeriesIdRoute
  ApiDebugXtreamRoute: typeof ApiDebugXtreamRoute
  WatchKindIdRoute: typeof WatchKindIdRoute
  ApiPublicStreamKindFileRoute: typeof ApiPublicStreamKindFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/series/$id': {
      id: '/series/$id'
      path: '/series/$id'
      fullPath: '/series/$id'
      preLoaderRoute: typeof SeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$kind': {
      id: '/browse/$kind'
      path: '/browse/$kind'
      fullPath: '/browse/$kind'
      preLoaderRoute: typeof BrowseKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/licenses': {
      id: '/admin/licenses'
      path: '/licenses'
      fullPath: '/admin/licenses'
      preLoaderRoute: typeof AdminLicensesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/codes': {
      id: '/admin/codes'
      path: '/codes'
      fullPath: '/admin/codes'
      preLoaderRoute: typeof AdminCodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/watch/$kind/$id': {
      id: '/watch/$kind/$id'
      path: '/watch/$kind/$id'
      fullPath: '/watch/$kind/$id'
      preLoaderRoute: typeof WatchKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/xtream': {
      id: '/api/debug/xtream'
      path: '/api/debug/xtream'
      fullPath: '/api/debug/xtream'
      preLoaderRoute: typeof ApiDebugXtreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stream/$kind/$file': {
      id: '/api/public/stream/$kind/$file'
      path: '/api/public/stream/$kind/$file'
      fullPath: '/api/public/stream/$kind/$file'
      preLoaderRoute: typeof ApiPublicStreamKindFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCodesRoute: typeof AdminCodesRoute
  AdminLicensesRoute: typeof AdminLicensesRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCodesRoute: AdminCodesRoute,
  AdminLicensesRoute: AdminLicensesRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BootstrapRoute: BootstrapRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  MoreRoute: MoreRoute,
  RedeemRoute: RedeemRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  BrowseKindRoute: BrowseKindRoute,
  MovieIdRoute: MovieIdRoute,
  SeriesIdRoute: SeriesIdRoute,
  ApiDebugXtreamRoute: ApiDebugXtreamRoute,
  WatchKindIdRoute: WatchKindIdRoute,
  ApiPublicStreamKindFileRoute: ApiPublicStreamKindFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
