/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SeriesIdRouteImport } from './routes/series.$id'
import { Route as MovieIdRouteImport } from './routes/movie.$id'
import { Route as BrowseKindRouteImport } from './routes/browse.$kind'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminSessionsRouteImport } from './routes/admin.sessions'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminResellersRouteImport } from './routes/admin.resellers'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLicensesRouteImport } from './routes/admin.licenses'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminDevicesRouteImport } from './routes/admin.devices'
import { Route as AdminCodesRouteImport } from './routes/admin.codes'
import { Route as AdminBulkRouteImport } from './routes/admin.bulk'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminApiRouteImport } from './routes/admin.api'
import { Route as AuthenticatedResellerRouteImport } from './routes/_authenticated/reseller'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as WatchKindIdRouteImport } from './routes/watch.$kind.$id'
import { Route as ApiV1PackagesRouteImport } from './routes/api.v1.packages'
import { Route as ApiV1OrdersRouteImport } from './routes/api.v1.orders'
import { Route as ApiV1OpenapiRouteImport } from './routes/api.v1.openapi'
import { Route as ApiV1LicensesRouteImport } from './routes/api.v1.licenses'
import { Route as ApiV1InvoicesRouteImport } from './routes/api.v1.invoices'
import { Route as ApiV1DocsRouteImport } from './routes/api.v1.docs'
import { Route as ApiDebugXtreamRouteImport } from './routes/api.debug.xtream'
import { Route as ApiV1WebhooksEndpointsRouteImport } from './routes/api.v1.webhooks.endpoints'
import { Route as ApiV1LicensesIdRouteImport } from './routes/api.v1.licenses.$id'
import { Route as ApiV1InvoicesIdRouteImport } from './routes/api.v1.invoices.$id'
import { Route as ApiV1HealthVersionRouteImport } from './routes/api.v1.health.version'
import { Route as ApiV1HealthReadyRouteImport } from './routes/api.v1.health.ready'
import { Route as ApiV1HealthLiveRouteImport } from './routes/api.v1.health.live'
import { Route as ApiAdminExportFileRouteImport } from './routes/api.admin.export.$file'
import { Route as ApiPublicStreamKindFileRouteImport } from './routes/api.public.stream.$kind.$file'
import { Route as ApiBillingInvoicesIdPdfRouteImport } from './routes/api.billing.invoices.$id.pdf'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SeriesIdRoute = SeriesIdRouteImport.update({
  id: '/series/$id',
  path: '/series/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseKindRoute = BrowseKindRouteImport.update({
  id: '/browse/$kind',
  path: '/browse/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResellersRoute = AdminResellersRouteImport.update({
  id: '/resellers',
  path: '/resellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLicensesRoute = AdminLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevicesRoute = AdminDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCodesRoute = AdminCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBulkRoute = AdminBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiRoute = AdminApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedResellerRoute = AuthenticatedResellerRouteImport.update({
  id: '/reseller',
  path: '/reseller',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const WatchKindIdRoute = WatchKindIdRouteImport.update({
  id: '/watch/$kind/$id',
  path: '/watch/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PackagesRoute = ApiV1PackagesRouteImport.update({
  id: '/api/v1/packages',
  path: '/api/v1/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OrdersRoute = ApiV1OrdersRouteImport.update({
  id: '/api/v1/orders',
  path: '/api/v1/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpenapiRoute = ApiV1OpenapiRouteImport.update({
  id: '/api/v1/openapi',
  path: '/api/v1/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LicensesRoute = ApiV1LicensesRouteImport.update({
  id: '/api/v1/licenses',
  path: '/api/v1/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1InvoicesRoute = ApiV1InvoicesRouteImport.update({
  id: '/api/v1/invoices',
  path: '/api/v1/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DocsRoute = ApiV1DocsRouteImport.update({
  id: '/api/v1/docs',
  path: '/api/v1/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugXtreamRoute = ApiDebugXtreamRouteImport.update({
  id: '/api/debug/xtream',
  path: '/api/debug/xtream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WebhooksEndpointsRoute = ApiV1WebhooksEndpointsRouteImport.update({
  id: '/api/v1/webhooks/endpoints',
  path: '/api/v1/webhooks/endpoints',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LicensesIdRoute = ApiV1LicensesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1LicensesRoute,
} as any)
const ApiV1InvoicesIdRoute = ApiV1InvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1InvoicesRoute,
} as any)
const ApiV1HealthVersionRoute = ApiV1HealthVersionRouteImport.update({
  id: '/api/v1/health/version',
  path: '/api/v1/health/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthReadyRoute = ApiV1HealthReadyRouteImport.update({
  id: '/api/v1/health/ready',
  path: '/api/v1/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthLiveRoute = ApiV1HealthLiveRouteImport.update({
  id: '/api/v1/health/live',
  path: '/api/v1/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminExportFileRoute = ApiAdminExportFileRouteImport.update({
  id: '/api/admin/export/$file',
  path: '/api/admin/export/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStreamKindFileRoute = ApiPublicStreamKindFileRouteImport.update({
  id: '/api/public/stream/$kind/$file',
  path: '/api/public/stream/$kind/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingInvoicesIdPdfRoute = ApiBillingInvoicesIdPdfRouteImport.update({
  id: '/api/billing/invoices/$id/pdf',
  path: '/api/billing/invoices/$id/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bootstrap': typeof BootstrapRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/redeem': typeof RedeemRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/reseller': typeof AuthenticatedResellerRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/bulk': typeof AdminBulkRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/resellers': typeof AdminResellersRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/browse/$kind': typeof BrowseKindRoute
  '/movie/$id': typeof MovieIdRoute
  '/series/$id': typeof SeriesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/debug/xtream': typeof ApiDebugXtreamRoute
  '/api/v1/docs': typeof ApiV1DocsRoute
  '/api/v1/invoices': typeof ApiV1InvoicesRouteWithChildren
  '/api/v1/licenses': typeof ApiV1LicensesRouteWithChildren
  '/api/v1/openapi': typeof ApiV1OpenapiRoute
  '/api/v1/orders': typeof ApiV1OrdersRoute
  '/api/v1/packages': typeof ApiV1PackagesRoute
  '/watch/$kind/$id': typeof WatchKindIdRoute
  '/api/admin/export/$file': typeof ApiAdminExportFileRoute
  '/api/v1/health/live': typeof ApiV1HealthLiveRoute
  '/api/v1/health/ready': typeof ApiV1HealthReadyRoute
  '/api/v1/health/version': typeof ApiV1HealthVersionRoute
  '/api/v1/invoices/$id': typeof ApiV1InvoicesIdRoute
  '/api/v1/licenses/$id': typeof ApiV1LicensesIdRoute
  '/api/v1/webhooks/endpoints': typeof ApiV1WebhooksEndpointsRoute
  '/api/billing/invoices/$id/pdf': typeof ApiBillingInvoicesIdPdfRoute
  '/api/public/stream/$kind/$file': typeof ApiPublicStreamKindFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bootstrap': typeof BootstrapRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/redeem': typeof RedeemRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/reseller': typeof AuthenticatedResellerRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/bulk': typeof AdminBulkRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/resellers': typeof AdminResellersRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/browse/$kind': typeof BrowseKindRoute
  '/movie/$id': typeof MovieIdRoute
  '/series/$id': typeof SeriesIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/debug/xtream': typeof ApiDebugXtreamRoute
  '/api/v1/docs': typeof ApiV1DocsRoute
  '/api/v1/invoices': typeof ApiV1InvoicesRouteWithChildren
  '/api/v1/licenses': typeof ApiV1LicensesRouteWithChildren
  '/api/v1/openapi': typeof ApiV1OpenapiRoute
  '/api/v1/orders': typeof ApiV1OrdersRoute
  '/api/v1/packages': typeof ApiV1PackagesRoute
  '/watch/$kind/$id': typeof WatchKindIdRoute
  '/api/admin/export/$file': typeof ApiAdminExportFileRoute
  '/api/v1/health/live': typeof ApiV1HealthLiveRoute
  '/api/v1/health/ready': typeof ApiV1HealthReadyRoute
  '/api/v1/health/version': typeof ApiV1HealthVersionRoute
  '/api/v1/invoices/$id': typeof ApiV1InvoicesIdRoute
  '/api/v1/licenses/$id': typeof ApiV1LicensesIdRoute
  '/api/v1/webhooks/endpoints': typeof ApiV1WebhooksEndpointsRoute
  '/api/billing/invoices/$id/pdf': typeof ApiBillingInvoicesIdPdfRoute
  '/api/public/stream/$kind/$file': typeof ApiPublicStreamKindFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/bootstrap': typeof BootstrapRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/redeem': typeof RedeemRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/reseller': typeof AuthenticatedResellerRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/bulk': typeof AdminBulkRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/resellers': typeof AdminResellersRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/browse/$kind': typeof BrowseKindRoute
  '/movie/$id': typeof MovieIdRoute
  '/series/$id': typeof SeriesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/debug/xtream': typeof ApiDebugXtreamRoute
  '/api/v1/docs': typeof ApiV1DocsRoute
  '/api/v1/invoices': typeof ApiV1InvoicesRouteWithChildren
  '/api/v1/licenses': typeof ApiV1LicensesRouteWithChildren
  '/api/v1/openapi': typeof ApiV1OpenapiRoute
  '/api/v1/orders': typeof ApiV1OrdersRoute
  '/api/v1/packages': typeof ApiV1PackagesRoute
  '/watch/$kind/$id': typeof WatchKindIdRoute
  '/api/admin/export/$file': typeof ApiAdminExportFileRoute
  '/api/v1/health/live': typeof ApiV1HealthLiveRoute
  '/api/v1/health/ready': typeof ApiV1HealthReadyRoute
  '/api/v1/health/version': typeof ApiV1HealthVersionRoute
  '/api/v1/invoices/$id': typeof ApiV1InvoicesIdRoute
  '/api/v1/licenses/$id': typeof ApiV1LicensesIdRoute
  '/api/v1/webhooks/endpoints': typeof ApiV1WebhooksEndpointsRoute
  '/api/billing/invoices/$id/pdf': typeof ApiBillingInvoicesIdPdfRoute
  '/api/public/stream/$kind/$file': typeof ApiPublicStreamKindFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bootstrap'
    | '/favorites'
    | '/login'
    | '/more'
    | '/redeem'
    | '/search'
    | '/settings'
    | '/portal'
    | '/reseller'
    | '/admin/api'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/bulk'
    | '/admin/codes'
    | '/admin/devices'
    | '/admin/jobs'
    | '/admin/licenses'
    | '/admin/notifications'
    | '/admin/packages'
    | '/admin/resellers'
    | '/admin/security'
    | '/admin/sessions'
    | '/admin/system'
    | '/admin/users'
    | '/browse/$kind'
    | '/movie/$id'
    | '/series/$id'
    | '/admin/'
    | '/api/debug/xtream'
    | '/api/v1/docs'
    | '/api/v1/invoices'
    | '/api/v1/licenses'
    | '/api/v1/openapi'
    | '/api/v1/orders'
    | '/api/v1/packages'
    | '/watch/$kind/$id'
    | '/api/admin/export/$file'
    | '/api/v1/health/live'
    | '/api/v1/health/ready'
    | '/api/v1/health/version'
    | '/api/v1/invoices/$id'
    | '/api/v1/licenses/$id'
    | '/api/v1/webhooks/endpoints'
    | '/api/billing/invoices/$id/pdf'
    | '/api/public/stream/$kind/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bootstrap'
    | '/favorites'
    | '/login'
    | '/more'
    | '/redeem'
    | '/search'
    | '/settings'
    | '/portal'
    | '/reseller'
    | '/admin/api'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/bulk'
    | '/admin/codes'
    | '/admin/devices'
    | '/admin/jobs'
    | '/admin/licenses'
    | '/admin/notifications'
    | '/admin/packages'
    | '/admin/resellers'
    | '/admin/security'
    | '/admin/sessions'
    | '/admin/system'
    | '/admin/users'
    | '/browse/$kind'
    | '/movie/$id'
    | '/series/$id'
    | '/admin'
    | '/api/debug/xtream'
    | '/api/v1/docs'
    | '/api/v1/invoices'
    | '/api/v1/licenses'
    | '/api/v1/openapi'
    | '/api/v1/orders'
    | '/api/v1/packages'
    | '/watch/$kind/$id'
    | '/api/admin/export/$file'
    | '/api/v1/health/live'
    | '/api/v1/health/ready'
    | '/api/v1/health/version'
    | '/api/v1/invoices/$id'
    | '/api/v1/licenses/$id'
    | '/api/v1/webhooks/endpoints'
    | '/api/billing/invoices/$id/pdf'
    | '/api/public/stream/$kind/$file'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/bootstrap'
    | '/favorites'
    | '/login'
    | '/more'
    | '/redeem'
    | '/search'
    | '/settings'
    | '/_authenticated/portal'
    | '/_authenticated/reseller'
    | '/admin/api'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/bulk'
    | '/admin/codes'
    | '/admin/devices'
    | '/admin/jobs'
    | '/admin/licenses'
    | '/admin/notifications'
    | '/admin/packages'
    | '/admin/resellers'
    | '/admin/security'
    | '/admin/sessions'
    | '/admin/system'
    | '/admin/users'
    | '/browse/$kind'
    | '/movie/$id'
    | '/series/$id'
    | '/admin/'
    | '/api/debug/xtream'
    | '/api/v1/docs'
    | '/api/v1/invoices'
    | '/api/v1/licenses'
    | '/api/v1/openapi'
    | '/api/v1/orders'
    | '/api/v1/packages'
    | '/watch/$kind/$id'
    | '/api/admin/export/$file'
    | '/api/v1/health/live'
    | '/api/v1/health/ready'
    | '/api/v1/health/version'
    | '/api/v1/invoices/$id'
    | '/api/v1/licenses/$id'
    | '/api/v1/webhooks/endpoints'
    | '/api/billing/invoices/$id/pdf'
    | '/api/public/stream/$kind/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  BootstrapRoute: typeof BootstrapRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  MoreRoute: typeof MoreRoute
  RedeemRoute: typeof RedeemRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  BrowseKindRoute: typeof BrowseKindRoute
  MovieIdRoute: typeof MovieIdRoute
  SeriesIdRoute: typeof SeriesIdRoute
  ApiDebugXtreamRoute: typeof ApiDebugXtreamRoute
  ApiV1DocsRoute: typeof ApiV1DocsRoute
  ApiV1InvoicesRoute: typeof ApiV1InvoicesRouteWithChildren
  ApiV1LicensesRoute: typeof ApiV1LicensesRouteWithChildren
  ApiV1OpenapiRoute: typeof ApiV1OpenapiRoute
  ApiV1OrdersRoute: typeof ApiV1OrdersRoute
  ApiV1PackagesRoute: typeof ApiV1PackagesRoute
  WatchKindIdRoute: typeof WatchKindIdRoute
  ApiAdminExportFileRoute: typeof ApiAdminExportFileRoute
  ApiV1HealthLiveRoute: typeof ApiV1HealthLiveRoute
  ApiV1HealthReadyRoute: typeof ApiV1HealthReadyRoute
  ApiV1HealthVersionRoute: typeof ApiV1HealthVersionRoute
  ApiV1WebhooksEndpointsRoute: typeof ApiV1WebhooksEndpointsRoute
  ApiBillingInvoicesIdPdfRoute: typeof ApiBillingInvoicesIdPdfRoute
  ApiPublicStreamKindFileRoute: typeof ApiPublicStreamKindFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/series/$id': {
      id: '/series/$id'
      path: '/series/$id'
      fullPath: '/series/$id'
      preLoaderRoute: typeof SeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$kind': {
      id: '/browse/$kind'
      path: '/browse/$kind'
      fullPath: '/browse/$kind'
      preLoaderRoute: typeof BrowseKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resellers': {
      id: '/admin/resellers'
      path: '/resellers'
      fullPath: '/admin/resellers'
      preLoaderRoute: typeof AdminResellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/licenses': {
      id: '/admin/licenses'
      path: '/licenses'
      fullPath: '/admin/licenses'
      preLoaderRoute: typeof AdminLicensesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devices': {
      id: '/admin/devices'
      path: '/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AdminDevicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/codes': {
      id: '/admin/codes'
      path: '/codes'
      fullPath: '/admin/codes'
      preLoaderRoute: typeof AdminCodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bulk': {
      id: '/admin/bulk'
      path: '/bulk'
      fullPath: '/admin/bulk'
      preLoaderRoute: typeof AdminBulkRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api': {
      id: '/admin/api'
      path: '/api'
      fullPath: '/admin/api'
      preLoaderRoute: typeof AdminApiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/reseller': {
      id: '/_authenticated/reseller'
      path: '/reseller'
      fullPath: '/reseller'
      preLoaderRoute: typeof AuthenticatedResellerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/watch/$kind/$id': {
      id: '/watch/$kind/$id'
      path: '/watch/$kind/$id'
      fullPath: '/watch/$kind/$id'
      preLoaderRoute: typeof WatchKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/packages': {
      id: '/api/v1/packages'
      path: '/api/v1/packages'
      fullPath: '/api/v1/packages'
      preLoaderRoute: typeof ApiV1PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/orders': {
      id: '/api/v1/orders'
      path: '/api/v1/orders'
      fullPath: '/api/v1/orders'
      preLoaderRoute: typeof ApiV1OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/openapi': {
      id: '/api/v1/openapi'
      path: '/api/v1/openapi'
      fullPath: '/api/v1/openapi'
      preLoaderRoute: typeof ApiV1OpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/licenses': {
      id: '/api/v1/licenses'
      path: '/api/v1/licenses'
      fullPath: '/api/v1/licenses'
      preLoaderRoute: typeof ApiV1LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/invoices': {
      id: '/api/v1/invoices'
      path: '/api/v1/invoices'
      fullPath: '/api/v1/invoices'
      preLoaderRoute: typeof ApiV1InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/docs': {
      id: '/api/v1/docs'
      path: '/api/v1/docs'
      fullPath: '/api/v1/docs'
      preLoaderRoute: typeof ApiV1DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/xtream': {
      id: '/api/debug/xtream'
      path: '/api/debug/xtream'
      fullPath: '/api/debug/xtream'
      preLoaderRoute: typeof ApiDebugXtreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/webhooks/endpoints': {
      id: '/api/v1/webhooks/endpoints'
      path: '/api/v1/webhooks/endpoints'
      fullPath: '/api/v1/webhooks/endpoints'
      preLoaderRoute: typeof ApiV1WebhooksEndpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/licenses/$id': {
      id: '/api/v1/licenses/$id'
      path: '/$id'
      fullPath: '/api/v1/licenses/$id'
      preLoaderRoute: typeof ApiV1LicensesIdRouteImport
      parentRoute: typeof ApiV1LicensesRoute
    }
    '/api/v1/invoices/$id': {
      id: '/api/v1/invoices/$id'
      path: '/$id'
      fullPath: '/api/v1/invoices/$id'
      preLoaderRoute: typeof ApiV1InvoicesIdRouteImport
      parentRoute: typeof ApiV1InvoicesRoute
    }
    '/api/v1/health/version': {
      id: '/api/v1/health/version'
      path: '/api/v1/health/version'
      fullPath: '/api/v1/health/version'
      preLoaderRoute: typeof ApiV1HealthVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health/ready': {
      id: '/api/v1/health/ready'
      path: '/api/v1/health/ready'
      fullPath: '/api/v1/health/ready'
      preLoaderRoute: typeof ApiV1HealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health/live': {
      id: '/api/v1/health/live'
      path: '/api/v1/health/live'
      fullPath: '/api/v1/health/live'
      preLoaderRoute: typeof ApiV1HealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/export/$file': {
      id: '/api/admin/export/$file'
      path: '/api/admin/export/$file'
      fullPath: '/api/admin/export/$file'
      preLoaderRoute: typeof ApiAdminExportFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stream/$kind/$file': {
      id: '/api/public/stream/$kind/$file'
      path: '/api/public/stream/$kind/$file'
      fullPath: '/api/public/stream/$kind/$file'
      preLoaderRoute: typeof ApiPublicStreamKindFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/invoices/$id/pdf': {
      id: '/api/billing/invoices/$id/pdf'
      path: '/api/billing/invoices/$id/pdf'
      fullPath: '/api/billing/invoices/$id/pdf'
      preLoaderRoute: typeof ApiBillingInvoicesIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedResellerRoute: typeof AuthenticatedResellerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedResellerRoute: AuthenticatedResellerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminApiRoute: typeof AdminApiRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminBulkRoute: typeof AdminBulkRoute
  AdminCodesRoute: typeof AdminCodesRoute
  AdminDevicesRoute: typeof AdminDevicesRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminLicensesRoute: typeof AdminLicensesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminResellersRoute: typeof AdminResellersRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApiRoute: AdminApiRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminBulkRoute: AdminBulkRoute,
  AdminCodesRoute: AdminCodesRoute,
  AdminDevicesRoute: AdminDevicesRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminLicensesRoute: AdminLicensesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminResellersRoute: AdminResellersRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiV1InvoicesRouteChildren {
  ApiV1InvoicesIdRoute: typeof ApiV1InvoicesIdRoute
}

const ApiV1InvoicesRouteChildren: ApiV1InvoicesRouteChildren = {
  ApiV1InvoicesIdRoute: ApiV1InvoicesIdRoute,
}

const ApiV1InvoicesRouteWithChildren = ApiV1InvoicesRoute._addFileChildren(
  ApiV1InvoicesRouteChildren,
)

interface ApiV1LicensesRouteChildren {
  ApiV1LicensesIdRoute: typeof ApiV1LicensesIdRoute
}

const ApiV1LicensesRouteChildren: ApiV1LicensesRouteChildren = {
  ApiV1LicensesIdRoute: ApiV1LicensesIdRoute,
}

const ApiV1LicensesRouteWithChildren = ApiV1LicensesRoute._addFileChildren(
  ApiV1LicensesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  BootstrapRoute: BootstrapRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  MoreRoute: MoreRoute,
  RedeemRoute: RedeemRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  BrowseKindRoute: BrowseKindRoute,
  MovieIdRoute: MovieIdRoute,
  SeriesIdRoute: SeriesIdRoute,
  ApiDebugXtreamRoute: ApiDebugXtreamRoute,
  ApiV1DocsRoute: ApiV1DocsRoute,
  ApiV1InvoicesRoute: ApiV1InvoicesRouteWithChildren,
  ApiV1LicensesRoute: ApiV1LicensesRouteWithChildren,
  ApiV1OpenapiRoute: ApiV1OpenapiRoute,
  ApiV1OrdersRoute: ApiV1OrdersRoute,
  ApiV1PackagesRoute: ApiV1PackagesRoute,
  WatchKindIdRoute: WatchKindIdRoute,
  ApiAdminExportFileRoute: ApiAdminExportFileRoute,
  ApiV1HealthLiveRoute: ApiV1HealthLiveRoute,
  ApiV1HealthReadyRoute: ApiV1HealthReadyRoute,
  ApiV1HealthVersionRoute: ApiV1HealthVersionRoute,
  ApiV1WebhooksEndpointsRoute: ApiV1WebhooksEndpointsRoute,
  ApiBillingInvoicesIdPdfRoute: ApiBillingInvoicesIdPdfRoute,
  ApiPublicStreamKindFileRoute: ApiPublicStreamKindFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
